### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by byposeidon** [v4d1/Dome#1]
I have added api for all services but they are not working because these services are not receiving requests.

python version: 3.6.9
config.api -> VIRUSTOTAL, SHODAN, SECURITYTRAILS, PASSIVETOTAL, BINARYEDGE.

**Comment by v4d1** [comment]
I am on vacations, i'll check it and fix it in 2 weeks

**Comment by v4d1** [comment]
Fixed OSINT search engines.
